version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5570:8080"
    environment:
      - "ConnectionStrings:RestApiDb=${CONNECTION_STRING}"
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - rest-api-db

  rest-api-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
